version: '3.1'
services:
  scripthash_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scripthash_server
    ports: 
    - 9000:8080
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 100m  